# browsershots.org - Test your web design in different browsers
# Copyright (C) 2007 Johann C. Rocholl <johann@browsershots.org>
#
# Browsershots is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# Browsershots is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

"""
Convert two-letter country codes to human-readable names.
"""

__revision__ = "$Rev: 2968 $"
__date__ = "$Date: 2008-08-14 07:34:01 -0300 (qui, 14 ago 2008) $"
__author__ = "$Author: johann $"

from django import template


COUNTRIES = (
    ('AF', "Afghanistan"),
    ('AX', "Aland Islands"),
    ('AL', "Albania"),
    ('DZ', "Algeria"),
    ('AS', "American Samoa"),
    ('AD', "Andorra"),
    ('AO', "Angola"),
    ('AI', "Anguilla"),
    ('AQ', "Antarctica"),
    ('AG', "Antigua And Barbuda"),
    ('AR', "Argentina"),
    ('AM', "Armenia"),
    ('AW', "Aruba"),
    ('AU', "Australia"),
    ('AT', "Austria"),
    ('AZ', "Azerbaijan"),
    ('BS', "Bahamas"),
    ('BH', "Bahrain"),
    ('BD', "Bangladesh"),
    ('BB', "Barbados"),
    ('BY', "Belarus"),
    ('BE', "Belgium"),
    ('BZ', "Belize"),
    ('BJ', "Benin"),
    ('BM', "Bermuda"),
    ('BT', "Bhutan"),
    ('BO', "Bolivia"),
    ('BA', "Bosnia And Herzegovina"),
    ('BW', "Botswana"),
    ('BV', "Bouvet Island"),
    ('BR', "Brazil"),
    ('IO', "British Indian Ocean Territory"),
    ('BN', "Brunei Darussalam"),
    ('BG', "Bulgaria"),
    ('BF', "Burkina Faso"),
    ('BI', "Burundi"),
    ('KH', "Cambodia"),
    ('CM', "Cameroon"),
    ('CA', "Canada"),
    ('CV', "Cape Verde"),
    ('KY', "Cayman Islands"),
    ('CF', "Central African Republic"),
    ('TD', "Chad"),
    ('CL', "Chile"),
    ('CN', "China"),
    ('CX', "Christmas Island"),
    ('CC', "Cocos (Keeling) Islands"),
    ('CO', "Colombia"),
    ('KM', "Comoros"),
    ('CG', "Congo"),
    ('CD', "Congo, The Democratic Republic Of The"),
    ('CK', "Cook Islands"),
    ('CR', "Costa Rica"),
    ('CI', "Cote D'Ivoire"),
    ('HR', "Croatia"),
    ('CU', "Cuba"),
    ('CY', "Cyprus"),
    ('CZ', "Czech Republic"),
    ('DK', "Denmark"),
    ('DJ', "Djibouti"),
    ('DM', "Dominica"),
    ('DO', "Dominican Republic"),
    ('EC', "Ecuador"),
    ('EG', "Egypt"),
    ('SV', "El Salvador"),
    ('GQ', "Equatorial Guinea"),
    ('ER', "Eritrea"),
    ('EE', "Estonia"),
    ('ET', "Ethiopia"),
    ('FK', "Falkland Islands (Malvinas)"),
    ('FO', "Faroe Islands"),
    ('FJ', "Fiji"),
    ('FI', "Finland"),
    ('FR', "France"),
    ('GF', "French Guiana"),
    ('PF', "French Polynesia"),
    ('TF', "French Southern Territories"),
    ('GA', "Gabon"),
    ('GM', "Gambia"),
    ('GE', "Georgia"),
    ('DE', "Germany"),
    ('GH', "Ghana"),
    ('GI', "Gibraltar"),
    ('GR', "Greece"),
    ('GL', "Greenland"),
    ('GD', "Grenada"),
    ('GP', "Guadeloupe"),
    ('GU', "Guam"),
    ('GT', "Guatemala"),
    ('GG', "Guernsey"),
    ('GN', "Guinea"),
    ('GW', "Guinea-Bissau"),
    ('GY', "Guyana"),
    ('HT', "Haiti"),
    ('HM', "Heard Island And Mcdonald Islands"),
    ('VA', "Holy See (Vatican City State)"),
    ('HN', "Honduras"),
    ('HK', "Hong Kong"),
    ('HU', "Hungary"),
    ('IS', "Iceland"),
    ('IN', "India"),
    ('ID', "Indonesia"),
    ('IR', "Iran, Islamic Republic Of"),
    ('IQ', "Iraq"),
    ('IE', "Ireland"),
    ('IM', "Isle Of Man"),
    ('IL', "Israel"),
    ('IT', "Italy"),
    ('JM', "Jamaica"),
    ('JP', "Japan"),
    ('JE', "Jersey"),
    ('JO', "Jordan"),
    ('KZ', "Kazakhstan"),
    ('KE', "Kenya"),
    ('KI', "Kiribati"),
    ('KP', "Korea, Democratic People's Republic Of"),
    ('KR', "Korea, Republic Of"),
    ('KW', "Kuwait"),
    ('KG', "Kyrgyzstan"),
    ('LA', "Lao People's Democratic Republic"),
    ('LV', "Latvia"),
    ('LB', "Lebanon"),
    ('LS', "Lesotho"),
    ('LR', "Liberia"),
    ('LY', "Libyan Arab Jamahiriya"),
    ('LI', "Liechtenstein"),
    ('LT', "Lithuania"),
    ('LU', "Luxembourg"),
    ('MO', "Macao"),
    ('MK', "Macedonia, The Former Yugoslav Republic Of"),
    ('MG', "Madagascar"),
    ('MW', "Malawi"),
    ('MY', "Malaysia"),
    ('MV', "Maldives"),
    ('ML', "Mali"),
    ('MT', "Malta"),
    ('MH', "Marshall Islands"),
    ('MQ', "Martinique"),
    ('MR', "Mauritania"),
    ('MU', "Mauritius"),
    ('YT', "Mayotte"),
    ('MX', "Mexico"),
    ('FM', "Micronesia, Federated States Of"),
    ('MD', "Moldova, Republic Of"),
    ('MC', "Monaco"),
    ('MN', "Mongolia"),
    ('ME', "Montenegro"),
    ('MS', "Montserrat"),
    ('MA', "Morocco"),
    ('MZ', "Mozambique"),
    ('MM', "Myanmar"),
    ('NA', "Namibia"),
    ('NR', "Nauru"),
    ('NP', "Nepal"),
    ('NL', "Netherlands"),
    ('AN', "Netherlands Antilles"),
    ('NC', "New Caledonia"),
    ('NZ', "New Zealand"),
    ('NI', "Nicaragua"),
    ('NE', "Niger"),
    ('NG', "Nigeria"),
    ('NU', "Niue"),
    ('NF', "Norfolk Island"),
    ('MP', "Northern Mariana Islands"),
    ('NO', "Norway"),
    ('OM', "Oman"),
    ('PK', "Pakistan"),
    ('PW', "Palau"),
    ('PS', "Palestinian Territory, Occupied"),
    ('PA', "Panama"),
    ('PG', "Papua New Guinea"),
    ('PY', "Paraguay"),
    ('PE', "Peru"),
    ('PH', "Philippines"),
    ('PN', "Pitcairn"),
    ('PL', "Poland"),
    ('PT', "Portugal"),
    ('PR', "Puerto Rico"),
    ('QA', "Qatar"),
    ('RE', "Reunion"),
    ('RO', "Romania"),
    ('RU', "Russian Federation"),
    ('RW', "Rwanda"),
    ('BL', "Saint Barthelemy"),
    ('SH', "Saint Helena"),
    ('KN', "Saint Kitts And Nevis"),
    ('LC', "Saint Lucia"),
    ('MF', "Saint Martin"),
    ('PM', "Saint Pierre And Miquelon"),
    ('VC', "Saint Vincent And The Grenadines"),
    ('WS', "Samoa"),
    ('SM', "San Marino"),
    ('ST', "Sao Tome And Principe"),
    ('SA', "Saudi Arabia"),
    ('SN', "Senegal"),
    ('RS', "Serbia"),
    ('SC', "Seychelles"),
    ('SL', "Sierra Leone"),
    ('SG', "Singapore"),
    ('SK', "Slovakia"),
    ('SI', "Slovenia"),
    ('SB', "Solomon Islands"),
    ('SO', "Somalia"),
    ('ZA', "South Africa"),
    ('GS', "South Georgia And The South Sandwich Islands"),
    ('ES', "Spain"),
    ('LK', "Sri Lanka"),
    ('SD', "Sudan"),
    ('SR', "Suriname"),
    ('SJ', "Svalbard And Jan Mayen"),
    ('SZ', "Swaziland"),
    ('SE', "Sweden"),
    ('CH', "Switzerland"),
    ('SY', "Syrian Arab Republic"),
    ('TW', "Taiwan, Province Of China"),
    ('TJ', "Tajikistan"),
    ('TZ', "Tanzania, United Republic Of"),
    ('TH', "Thailand"),
    ('TL', "Timor-Leste"),
    ('TG', "Togo"),
    ('TK', "Tokelau"),
    ('TO', "Tonga"),
    ('TT', "Trinidad And Tobago"),
    ('TN', "Tunisia"),
    ('TR', "Turkey"),
    ('TM', "Turkmenistan"),
    ('TC', "Turks And Caicos Islands"),
    ('TV', "Tuvalu"),
    ('UG', "Uganda"),
    ('UA', "Ukraine"),
    ('AE', "United Arab Emirates"),
    ('GB', "United Kingdom"),
    ('US', "United States"),
    ('UM', "United States Minor Outlying Islands"),
    ('UY', "Uruguay"),
    ('UZ', "Uzbekistan"),
    ('VU', "Vanuatu"),
    ('VE', "Venezuela"),
    ('VN', "Viet Nam"),
    ('VG', "Virgin Islands, British"),
    ('VI', "Virgin Islands, U.S."),
    ('WF', "Wallis And Futuna"),
    ('EH', "Western Sahara"),
    ('YE', "Yemen"),
    ('ZM', "Zambia"),
    ('ZW', "Zimbabwe"),
    )


register = template.Library()


@register.filter
def country_name(two_letter_code):
    for code, name in COUNTRIES:
        if code == two_letter_code:
            return name
    return two_letter_code
